-- This module is the root of the GeneralizedHodgeConjectureCanonicalLaneLean Lean proof package.
import GeneralizedHodgeConjectureCanonicalLaneLean.Basic
import GeneralizedHodgeConjectureCanonicalLaneLean.SourcePackage
import GeneralizedHodgeConjectureCanonicalLaneLean.SourceDependencies
import GeneralizedHodgeConjectureCanonicalLaneLean.Formalization
import GeneralizedHodgeConjectureCanonicalLaneLean.ReviewerBridge
import GeneralizedHodgeConjectureCanonicalLaneLean.TheoremStatement
import GeneralizedHodgeConjectureCanonicalLaneLean.MathlibObjects
import GeneralizedHodgeConjectureCanonicalLaneLean.AdmissibleClass
import GeneralizedHodgeConjectureCanonicalLaneLean.Projection
import GeneralizedHodgeConjectureCanonicalLaneLean.BridgeLemmas
import GeneralizedHodgeConjectureCanonicalLaneLean.GateLemmas
import GeneralizedHodgeConjectureCanonicalLaneLean.FinalTheorem
import GeneralizedHodgeConjectureCanonicalLaneLean.MathlibStatement
